# -*- coding: utf-8 -*-
"""Internal_assessment_python1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ids-ppAjTEqbKltfTC5EVIqKic7WpyHC
"""

# 1

l=int(input("Enter the Length of the rectangle"))
b=int(input("Enter the Breadth of the rectangle"))
area=l*b
print(f"Area of the rectangle is {area}")

#2

weight=float(input("Enter your weight in Kg"))
height=float(input("Enter your height in meter"))
BMI=weight/(height)**2
print(f"BMI is {BMI}")

# 3
students={}
n=int(input("Enter Number of the students"))
for i in range (n):
  name=input("Enter Students name")
  scores=input("Enter Score of the student")
  students[name]=scores
print(students)

#4

age=int(input("Enter Your age"))
if(age<=15):
  print("Minor")
elif(age<=25 and age<=45):
  print("Adult")
else:
  print("Senior")

#5

for i in range(1,50):
  if(i%2==0):
    print(i,end=" ")
  else:
    pass

# 6

password="Hello"
while(True):
  p=input("Enter your password")
  if(p==password):
    print("Congrats You Entered Right Password")
    break
  else:
    print("Try Again")
    continue

#7


def calculate_average(numbers):
    if not numbers:
        return None
    c=sum(numbers)/len(numbers)
    return c

numbers = list(map(int,input("Enter Number List").split()))
average = calculate_average(numbers)
print(f"Average of the list is {average} .")

# 8
def count_vowel(s):
  count=0
  for i in s:
    if (i=='a' or i=='e' or i=='i'or i=='o' or i=='u'):
      count+=1
  return count
s=input("Enter your String")
print(f"Number of vowel in the string is {count_vowel(s)}")

#9

from datetime import datetime
current_date_time=datetime.now()
print(f"The current date and time is {current_date_time}")

# 10

n=int(input("Enter the number"))
m=int(input("Enter the other number"))
e=input("Enter other number")
def addition(a,b,c):
  try:
    z=m+e
  except TypeError:
    print("Can't be added non numeric input")
  z=n+m
print(f"the sum of the number are {z}")
addition(n,m,e)

#11
i=input()
try:
  print i

except ValueError:
  print("The value u entered is not integer")

# 12


def division(a,b):
  try:
    z=a/b
    print(z)
  except ZeroDivisionError:
    print("Number can't be divided by 0")

n=int(input("Enter the number"))
m=int(input("Enter the other number"))
division(n,m)

# 13


def writting_to_file(filename, content):
    with open(filename, 'w') as file:
        file.write(content)

filename = 'hello_python.txt'
content = 'hello python'

writting_to_file(filename, content)
print(f'Content "{content}" has been written to the file "{filename}".')

#14

file=open('/content/hello_python.txt','r')
reading_from_file=file.readlines()
print(reading_from_file)

# 15


file=open('/content/hello_python.txt','w')
writing_on_file=file.writelines("Hello,Python!")
writing_on_file=file.writelines("I am Utkarsh Anand from LVA")
file.close()
file=open('/content/hello_python.txt','r')
reading_from_file=file.readlines()
print(reading_from_file)