# -*- coding: utf-8 -*-
"""LVADSUSR127-Utkarsh Anand Lab1 Regression_Problem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14FOEesd2u3kzl-MYZIly2NXQkHJdEXfV
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from scipy.stats import zscore

data=pd.read_csv("/content/sample_data/expenses.csv")
df=pd.DataFrame(data)
df.isnull().sum()
df.head()
df.duplicated().sum()
df.drop_duplicates()
df.info()
df.describe()
plt.boxplot(df["bmi"])
plt.show()
plt.boxplot(df["charges"])
plt.show()
threshold = 3.0
z_scores = zscore(df["bmi"])
z_scores=zscore(df["charges"])
outliers = np.abs(z_scores) > threshold
cleaned_data = data[~outliers]
df.head()
X=df.drop("charges",axis="columns")
Y=df.charges
label_encoder=LabelEncoder()
X['sex']=label_encoder.fit_transform(X['sex'])
X['smoker']=label_encoder.fit_transform(X['smoker'])
X['region']=label_encoder.fit_transform(X['region'])

sns.pairplot(df,y_vars=['charges'])
plt.show()

print(X.corr())
sns.heatmap(X.corr(),cmap="jet",annot=True)
plt.show()

X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size =0.2,random_state=42)
model=LinearRegression()
model.fit(X_train,Y_train)
pred=model.predict(X_test)
R2=r2_score(Y_test,pred)
print(f"R2 score is {R2}")
mse=mean_squared_error(Y_test,pred)
print(f"The mean squared error for this model is {mse}")
rmse=np.sqrt(mse)
print(f"The root mean squared error for this model is {rmse}")