# -*- coding: utf-8 -*-
"""LVADSUSR127-Utkarsh Anand-L2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CDUFuWJkU77VybK2YsSK7h1Wihh5kmWo
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from scipy.stats import zscore
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from math import sqrt
data = pd.read_csv("/content/sample_data/auto-mpg.csv")
df=pd.DataFrame(data)
df.head()
df.isnull().sum()
df.fillna(df.mean(),inplace=True)

print(df.info())
print(df.describe())
print(df.duplicated().sum())
print(df.drop_duplicates())

label_encoder=LabelEncoder()
df['horsepower']=label_encoder.fit_transform(df['horsepower'])
df['car name']=label_encoder.fit_transform(df['car name'])
df.head()

plt.figure(figsize=(10, 6))
sns.boxplot(df)
plt.show()

threshold = 3.0
z_scores = zscore(df)
z_scores=zscore(df)
outliers = np.abs(z_scores) > threshold
df = df[~outliers]
plt.figure(figsize=(10, 6))
sns.boxplot(df)
plt.show()

print(df.corr())
plt.figure(figsize=(10, 6))
sns.heatmap(df.corr(),cmap="viridis",annot=True)
plt.show()

sns.pairplot(df,y_vars="car name")
plt.show()

X=df.iloc[:,1:]
X.fillna(X.mean(),inplace=True)
print(X)
Y=df.iloc[:,0]
print(Y)
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

model = LinearRegression()
model.fit(X_train,Y_train)
pred = model.predict(X_test)

accuracy = model.score(X_test, Y_test)

MSE = mean_squared_error(Y_test, pred)

R_squared = r2_score(Y_test, pred)

RMSE = sqrt(MSE)

print("Accuracy:", accuracy)
print("MSE:", MSE)
print("R-squared:", R_squared)
print("RMSE:", RMSE)

