# -*- coding: utf-8 -*-
"""LVADSUSR127-Utkarsh Anand-L4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GtRm6GdSQS4i1pqDL4Gq5Y6hsp_yIoCH
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import IsolationForest
import matplotlib.pyplot as plt
import seaborn as sns

import pandas as pd
data = pd.read_csv('/content/sample_data/social_network.csv')
df=pd.DataFrame(data)
df.columns

df.isnull().sum()

outlier_model = IsolationForest(contamination=0.1, random_state=42)
outliers = outlier_model.fit_predict(data[['login_activity', 'posting_activity', 'social_connections']])
data['is_outlier'] = outliers

data.describe()
print(data.shape)
print(data.info())
# Summary statistics
print(data.describe())

data.hist(figsize=(10, 8))
plt.tight_layout()
plt.show()

sns.pairplot(data, diag_kind='kde')
plt.show()

plt.figure(figsize=(10, 8))
sns.heatmap(data.corr(), annot=True, cmap='viridis', fmt='.2f')
plt.title('Correlation Heatmap')
plt.show()

label_encoder = LabelEncoder()
data['account_status'] = label_encoder.fit_transform(data['account_status'])

features = ['login_activity', 'posting_activity', 'social_connections']

X = data[features]
y = data['is_outlier']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = IsolationForest(n_estimators=100, contamination=0.1, max_features=3, max_samples=10000, random_state=42)
model.fit(X_train)
y_pred = model.predict(X_train)

data["anomaly_score"] = model.decision_function(X)

anomalies = data.loc[data["anomaly_score"] < 0]

plt.scatter(data["social_connections"], data["anomaly_score"], label="Not Anomaly")
plt.scatter(anomalies["social_connections"], anomalies["anomaly_score"], color="r", label="Anomaly")
plt.xlabel("Social Connections")
plt.ylabel("Anomaly Score")
plt.legend()
plt.show()